---
- name: Check whether /tmp/my.conf contains "127.0.0.1"
  command: grep -Fxq "*.* @@127.0.0.1:1514;RSYSLOG_FileFormat" /etc/rsyslog.d/alert-logic-agent.conf
  register: checkmyconf
  check_mode: no
  ignore_errors: yes
  changed_when: no
